Repository Arquisoft/wichat_es3a, pull requests merged in 2025-04, with the labels that each got.

#117 Optimización LLM service
  gatewayservice/gateway-service.js
  llmservice/llm-service.js
  webapp/src/components/Game/Game.tsx
  webapp/src/components/Game/LLMChat.tsx
Labels: enhancement, code, backend

#118 Optimización de preguntas
  questionservice/src/service/questionGeneratorService.js
  questionservice/src/service/questionService.js
  webapp/src/components/Game/Game.tsx
Labels: code, backend

#136 mejora en la carga de segundo plano
  gatewayservice/gateway-service.js
  questionservice/src/service/questionGeneratorService.js
  questionservice/src/service/questionSaverService.js
  questionservice/src/service/questionService.js
  webapp/src/components/Game/Game.tsx
  webapp/src/components/Game/Question/Question.tsx
  webapp/src/components/Main/Main.tsx
Labels: code, backend

#142 Modos de juego y mejora en las carga de preguntas
  gatewayservice/gateway-service.js
  questionservice/src/service/questionGeneratorService.js
  webapp/src/components/Game/Game.tsx
  webapp/src/components/Main/Main.tsx
  webapp/src/components/Main/MainQuestionGame.tsx
Labels: backend

#153 Rutas protegidas
  cardservice/package-lock.json
  webapp/src/router/AppRouter.tsx
  webapp/src/router/ProtectedRoute.tsx
Labels: bug, code

#156 Api key funcionando
  llmservice/llm-service.js
Labels: backend

#147 No acepteis ni cerreis esta PR es para ver que test van funcionando con cada commit besus
  .github/workflows/build.yml
  .github/workflows/release.yml
  gateway-api-service/gateway-api-service.test.js
  gateway-api-service/gatewayservice/.dockerignore
  gateway-api-service/gatewayservice/Dockerfile
  gateway-api-service/gatewayservice/README.md
  gateway-api-service/gatewayservice/gateway-api-service.test.js
  gateway-api-service/gatewayservice/openapi.yaml
  gateway-api-service/gatewayservice/package-lock.json
  gateway-api-service/gatewayservice/package.json
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  llmservice/llm-service.js
  llmservice/llm-service.test.js
  questionservice/src/utils/questionGenerator.ts
  questionservice/test/question-service.test.js
  sonar-project.properties
  webapp/e2e/steps/game-play.steps.js
  webapp/e2e/steps/historic-page.steps.js
  webapp/e2e/steps/login-form.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/e2e/test-environment-setup.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.test.tsx
  webapp/src/App.tsx
  webapp/src/components/AddUser/AddUser.test.tsx
  webapp/src/components/AddUser/AddUser.tsx
  webapp/src/components/Api/Api.test.tsx
  webapp/src/components/Api/Api.tsx
  webapp/src/components/Game/EndGame.test.tsx
  webapp/src/components/Game/EndGame.tsx
  webapp/src/components/Game/Game.test.tsx
  webapp/src/components/Game/Game.tsx
  webapp/src/components/Game/LLMChat.test.tsx
  webapp/src/components/Game/Question/Question.test.tsx
  webapp/src/components/Game/extras/CardGame.tsx
  webapp/src/components/Historic/Historic.test.tsx
  webapp/src/components/Historic/items/QuestionStat.test.tsx
  webapp/src/components/Historic/items/QuestionStat.tsx
  webapp/src/components/Login/Login.test.tsx
  webapp/src/components/Login/Login.tsx
  webapp/src/components/Main/Main.test.tsx
  webapp/src/components/Main/Main.tsx
  webapp/src/components/Main/MainQuestionGame.test.tsx
  webapp/src/components/Main/MainQuestionGame.tsx
  webapp/src/components/Main/items/NavBar.test.tsx
  webapp/src/components/Main/items/NavBar.tsx
  webapp/src/components/Ranking/Ranking.test.tsx
  webapp/src/components/Ranking/Ranking.tsx
  webapp/src/router/AppRouter.tsx
  webapp/src/router/ProtectedRoute.tsx
  webapp/src/setupTests.js
Labels: testing

#158 Acepté la otra sin querer asi que abro una nueva les go
  .github/workflows/build.yml
  .github/workflows/release.yml
  docker-compose.yml
  gateway-api-service/Dockerfile
  gateway-api-service/gateway-api-service.js
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  historicservice/Dockerfile
  historicservice/historic-service.test.js
  historicservice/historicService.js
  llmservice/llm-service.js
  questionservice/src/service/questionSaverService.js
  questionservice/src/service/questionService.js
  questionservice/test/question-service.test.js
  users/authservice/auth-service.test.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/src/components/AddUser/AddUser.tsx
  webapp/src/components/Game/Game.test.tsx
  webapp/src/components/Game/Game.tsx
  webapp/src/components/Game/LLMChat.test.tsx
  webapp/src/components/Game/LLMChat.tsx
  webapp/src/components/Game/extras/CardGame.tsx
  webapp/src/components/Historic/Historic.test.tsx
  webapp/src/components/Historic/Historic.tsx
  webapp/src/components/Login/Login.tsx
  webapp/src/components/Main/items/NavBar.test.tsx
Labels: code, testing
